### ISSUE TITLE
Have a jaspy meta-package

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jaspy-manager#26]
I want to be able to install jaspy without referring to the files in this repository. If there was a jaspy meta-package that included all the other packages as dependencies, I could do:

```
conda install -c https://dist.ceda.ac.uk/jaspy/jaspy3.7/version --override-channels jaspy
```

to get everything.

**Comment by mkjpryor-stfc** [comment]
Or `conda install -c ... 'jaspy==<release>'` to get a specific release.

**Comment by agstephens** [comment]
Historical
