### ISSUE TITLE
switch to sha256 for miniconda checksums

### ISSUE THREAD

**Issue by alaniwi** [cedadev/jaspy-manager#37]
SHA256 hashes are published at https://docs.conda.io/en/latest/miniconda.html / https://docs.conda.io/en/latest/miniconda_hashes.html so if used in jaspy-manager then adding a new version would just be a case of copying and pasting the hash from that web page into the `minicondas.json`.

**Comment by agstephens** [comment]
@alaniwi Feel free to make improvements to the code as you proceed :-)

**Comment by agstephens** [comment]
Historical
