### ISSUE TITLE
missing mamba

### ISSUE THREAD

**Issue by chrisbrierley** [cedadev/jaspy-manager#49]
I've had problems with the install_env_jaspy.sh script. It can't find mamba on L. 53

At present it tries to use a version of mamba explicitly from `$spec_file_path/bin`. But previously it had downloaded and installs mamba into the base environment. So there isn't a copy of mamba in the directly it looks in.

I got past this by removing `{$bin_dir}/` at the beginning of line 53

**Comment by agstephens** [comment]
Hi @chrisbrierley It looks like your solution fixes the problem. I have pushed the change to `master`. Please let me know if you see further issues.

Which environment are you trying to install?

**Comment by chrisbrierley** [comment]
Hi @agstephens, thanks for looking into it. I was installing jaspy3.7-m3-4.9.2-r20210320.

**Comment by agstephens** [comment]
👍
